[package]
name = "yew-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
wry-testing = { version = "0.1.0", path = ".." }
yew = { version = "0.22.0", features = ["csr"] }
yew-hooks = "0.4.0"
