[package]
name = "wry-bindgen-macro"
version = "0.2.106-alpha.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
wry-bindgen-macro-support = { path = "../wry-bindgen-macro-support", version = "=0.2.106-alpha.0" }
quote = "1"

[lints]
workspace = true
